services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secretpassword@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [
      "/app/wait-for.sh",
      "postgres:5432",
      "--",
      "/app/start-dev.sh"
    ]
    volumes:
      - ./:/app
    command: [ "air" ]